trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"
  timeoutInMinutes: 15

variables:
  python.version: "3.8"
  SONAR_HOST_URL: "https://sonarqube.imaginamos.com"
  SONAR_TOKEN: "sqa_ecda87f6f9e4b59bbde5d0730b3be1722513c848"
  SONAR_PROJECT_KEY: "test-prueba-devops"

steps:
  # 1. Configuraci칩n de Python
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(python.version)
      addToPath: true
    displayName: "Configurar Python $(python.version)"

  # 2. Instalaci칩n de dependencias
  - script: |
      python -m pip install --upgrade pip
      pip install pytest pytest-cov
    displayName: "Instalar dependencias"

  # 3. Descargar SonarScanner
  - script: |
      echo "##[group]Instalando SonarScanner"
      wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
      unzip sonar-scanner-cli-*.zip -d /opt
      rm sonar-scanner-cli-*.zip
      echo "##[endgroup]"
    displayName: "Instalar SonarScanner"

  # 4. Configurar entorno
  - script: |
      echo "##[group]Configurando entorno"
      echo "##vso[task.prependpath]$PWD/app"
      echo "##vso[task.prependpath]/opt/sonar-scanner-4.8.0.2856-linux/bin"
      echo "##[endgroup]"
    displayName: "Configurar paths"

  # 5. Ejecutar pruebas con cobertura
  - script: |
      echo "##[group]Ejecutando pruebas con cobertura"
      python -m pytest test/ --cov=app --cov-report=xml:coverage.xml -v --junitxml=test-results.xml
      echo "##[endgroup]"
    displayName: "Ejecutar pruebas"

  # 6. Ejecutar an치lisis SonarQube
  - script: |
      echo "##[group]Ejecutando an치lisis SonarQube"
      sonar-scanner \
        -Dsonar.projectKey=$(SONAR_PROJECT_KEY) \
        -Dsonar.projectName="test-prueba-devops" \
        -Dsonar.projectVersion=1.0 \
        -Dsonar.sources=app \
        -Dsonar.tests=test \
        -Dsonar.python.coverage.reportPaths=coverage.xml \
        -Dsonar.python.xunit.reportPath=test-results.xml \
        -Dsonar.host.url=$(SONAR_HOST_URL) \
        -Dsonar.login=$(SONAR_TOKEN) \
        -Dsonar.python.version=$(python.version)
      echo "##[endgroup]"
    displayName: "Analizar con SonarQube"
