trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.8"
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install pytest  # Instalamos pytest directamente aquí
    displayName: "Configurar entorno Python"

  - script: |
      if [ -f requirements.txt ]; then
        pip install -r requirements.txt
      fi
    displayName: "Instalar dependencias adicionales (si existen)"

  - script: |
      python -m pytest test/test_calculadora.py -v
    displayName: "Ejecutar pruebas unitarias"
