name: $(Build.DefinitionName)_destroy_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none # Evita ejecuci칩n autom치tica

variables:
  TF_VAR_location: "eastus"
  TF_VAR_environment: "dev"
  TF_VAR_resource_group_name: "rgtest"
  backend_storage_account: "tfbackendstorage"
  backend_container_name: "terraform-state"
  backend_key: "iac/terraform.tfstate"

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Terraform_Destroy
    displayName: "游댮 Destrucci칩n de Infraestructura en Azure"
    jobs:
      - job: DestroyInfra
        displayName: "Terraform Init & Destroy"
        steps:
          - task: UsePythonVersion@0
            displayName: "Seleccionar versi칩n de Python 3.x"
            inputs:
              versionSpec: "3.x"
              addToPath: true

          - task: TerraformTaskV4@4
            displayName: "游꺔 Terraform Init"
            inputs:
              provider: "azurerm"
              command: "init"
              workingDirectory: "$(System.DefaultWorkingDirectory)/iac"
              backendServiceArm: "ConexionAzureServicePrincipal1"
              backendAzureRmResourceGroupName: "rgtest"
              backendAzureRmStorageAccountName: "rgterraformdevops01"
              backendAzureRmContainerName: "terraform"
              backendAzureRmKey: "iac/terraform.tfstate"

          - task: TerraformTaskV4@4
            displayName: "游눢 Terraform Destroy"
            inputs:
              provider: "azurerm"
              command: "destroy"
              workingDirectory: "$(System.DefaultWorkingDirectory)/iac"
              environmentServiceNameAzureRM: "ConexionAzureServicePrincipal1"
