name: $(Build.DefinitionName)_CD_$(date:yyyyMMdd)$(rev:.r)

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  DOCKER_IMAGE_NAME: "test-prueba-devops"

stages:
  - stage: Deploy
    displayName: "Desplegar en AKS"
    jobs:
      - job: CD
        steps:
          - download:
              artifact: drop
              build:
                pipeline: CI-Pipeline-Calculadora en phyton
                project: Calculadora en phyton
                buildVersionToDownload: latest

          - task: AzureCLI@2
            inputs:
              azureSubscription: "ConexionAzureServicePrincipal1"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                for cluster in aks-cluster-1 aks-cluster-2; do
                  echo "⎈ Configurando $cluster"
                  az aks get-credentials --resource-group test-rg --name $cluster --overwrite-existing
                  kubectl apply -f k8s/configmap.yaml
                  kubectl apply -f k8s/deployment.yaml
                  kubectl apply -f k8s/ingress.yaml
                done
