trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"
  timeoutInMinutes: 20

variables:
  python.version: "3.8"
  SONAR_HOST_URL: "https://sonarqube.imaginamos.com"
  SONAR_TOKEN: $(SONAR_TOKEN_SECRET)
  SONAR_PROJECT_KEY: "test-prueba-devops"

stages:
  - stage: PruebasYAnalisis
    displayName: "Ejecutar pruebas y análisis"
    jobs:
      - job: TestYSonar
        displayName: "Ejecutar pruebas y analizar con SonarQube"
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: $(python.version)
              addToPath: true
            displayName: "Configurar Python"

          - script: |
              python -m pip install --upgrade pip
              pip install pytest pytest-cov
            displayName: "Instalar dependencias de pruebas"

          - script: |
              echo "##[group]Instalando SonarScanner"
              wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
              unzip sonar-scanner-cli-*.zip -d /opt
              rm sonar-scanner-cli-*.zip
              echo "##vso[task.prependpath]/opt/sonar-scanner-5.0.1.3006-linux/bin"
              echo "##[endgroup]"
            displayName: "Instalar SonarScanner"

          - script: |
              echo "##[group]Ejecución de pruebas"
              python -m pytest test/ --cov=app --cov-report=xml:coverage.xml -v --junitxml=test-results.xml
              echo "##[endgroup]"
            displayName: "Ejecutar pruebas"

          - script: |
              echo "##[group]Ejecutando análisis SonarQube"
              export PATH=/opt/sonar-scanner-5.0.1.3006-linux/bin:$PATH
              sonar-scanner \
                -Dsonar.projectKey=$(SONAR_PROJECT_KEY) \
                -Dsonar.projectName="test-prueba-devops" \
                -Dsonar.projectVersion=1.0 \
                -Dsonar.sources=app \
                -Dsonar.tests=test \
                -Dsonar.python.coverage.reportPaths=coverage.xml \
                -Dsonar.python.xunit.reportPath=test-results.xml \
                -Dsonar.host.url=$(SONAR_HOST_URL) \
                -Dsonar.login=$(SONAR_TOKEN) \
                -Dsonar.python.version=$(python.version)
              echo "##[endgroup]"
            displayName: "Analizar con SonarQube"
