trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.8"
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install pytest
    displayName: "Instalar dependencias"

  - script: |
      echo "Estructura del proyecto:"
      ls -R
      echo "Configurando PYTHONPATH..."
      echo "##vso[task.prependpath]$PWD/app"
    displayName: "Configurar entorno"

  - script: |
      python -m pytest test/test_calculadora.py -v
    displayName: "Ejecutar pruebas unitarias"
