trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"
  timeoutInMinutes: 20

variables:
  python.version: "3.8"
  SONAR_HOST_URL: "https://sonarqube.imaginamos.com"
  SONAR_TOKEN: $(SONAR_TOKEN_SECRET) # Define esta variable secreta en Azure DevOps
  SONAR_PROJECT_KEY: "test-prueba-devops"

steps:
  # 1. Verificar versi칩n de Java preinstalada
  - script: |
      echo "##[group]Versi칩n de Java"
      java -version
      echo "##[endgroup]"
    displayName: "Verificar Java preinstalado"

  # 2. Configurar Python
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(python.version)
      addToPath: true
    displayName: "Configurar Python $(python.version)"

  # 3. Instalar dependencias
  - script: |
      python -m pip install --upgrade pip
      pip install pytest pytest-cov
    displayName: "Instalar dependencias Python"

  # 4. Descargar SonarScanner compatible
  - script: |
      echo "##[group]Instalando SonarScanner"
      wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      unzip sonar-scanner-cli-*.zip -d /opt
      rm sonar-scanner-cli-*.zip
      echo "##[endgroup]"
    displayName: "Instalar SonarScanner"

  # 5. Configurar entorno
  - script: |
      echo "##[group]Configurando entorno"
      echo "##vso[task.prependpath]$PWD/app"
      echo "##vso[task.prependpath]/opt/sonar-scanner-5.0.1.3006-linux/bin"
      echo "##[endgroup]"
    displayName: "Configurar paths"

  # 6. Ejecutar pruebas con cobertura
  - script: |
      echo "##[group]Ejecutando pruebas con cobertura"
      python -m pytest test/ --cov=app --cov-report=xml:coverage.xml -v --junitxml=test-results.xml
      echo "##[endgroup]"
    displayName: "Ejecutar pruebas"

  # 7. Ejecutar an치lisis SonarQube
  - script: |
      echo "##[group]Ejecutando an치lisis SonarQube"
      sonar-scanner \
        -Dsonar.projectKey=$(SONAR_PROJECT_KEY) \
        -Dsonar.projectName="test-prueba-devops" \
        -Dsonar.projectVersion=1.0 \
        -Dsonar.sources=app \
        -Dsonar.tests=test \
        -Dsonar.python.coverage.reportPaths=coverage.xml \
        -Dsonar.python.xunit.reportPath=test-results.xml \
        -Dsonar.host.url=$(SONAR_HOST_URL) \
        -Dsonar.login=$(SONAR_TOKEN) \
        -Dsonar.python.version=$(python.version)
      echo "##[endgroup]"
    displayName: "Analizar con SonarQube"
